import type { Exercise, LessonFile, LessonMeta } from './types';
import meta from './meta.json';

// The whole curriculum is ~300 kB of JSON, and a visitor who only reads the
// landing page needs none of it. So the bundle carries just this index — every
// lesson's id/title/glyph/chapter, which is all the dashboard path draws — and
// each lesson's exercises arrive in their own chunk when the lesson is opened.
// `meta.json` is generated by `scripts/lesson.mjs`; `check` fails if it drifts.
export const LESSON_META: LessonMeta[] = meta as LessonMeta[];

// Keyed by id: './21-everyday-words.json' → 21. Only numeric-prefixed files are
// lessons, which is what keeps meta.json itself out of the glob.
const loaders = Object.fromEntries(
  Object.entries(
    import.meta.glob('./[0-9]*.json') as Record<string, () => Promise<{ default: LessonFile }>>
  ).map(([file, load]) => [parseInt(file.replace('./', ''), 10), load])
) as Record<number, () => Promise<{ default: LessonFile }>>;

/** A lesson's full file, or null if there's no such lesson. */
export async function loadLesson(id: number): Promise<LessonFile | null> {
  const load = loaders[id];
  return load ? (await load()).default : null;
}

/** Every lesson file, id-ascending. For tests and tooling — not the app. */
export async function loadAllLessons(): Promise<LessonFile[]> {
  const ids = Object.keys(loaders).map(Number).sort((a, b) => a - b);
  return Promise.all(ids.map(async (id) => (await loaders[id]()).default));
}

// The spine: the required, sequential path. Course length and progress are
// measured against this — branches are extra and never counted here.
export const SPINE_META: LessonMeta[] = LESSON_META.filter((l) => !l.optional);

// The optional branch lessons anchored to a given spine lesson.
export function branchesFor(anchorId: number): LessonMeta[] {
  return LESSON_META.filter((l) => l.optional && l.anchor === anchorId);
}

export type Chapter = {
  id: number;
  title: string;
  subtitle: string;
  comingSoon?: boolean;
  blurb?: string;
};

export const CHAPTERS: Chapter[] = [
  { id: 1, title: 'Chapter 1', subtitle: 'The Alphabet' },
  { id: 2, title: 'Chapter 2', subtitle: 'Reading Fluency' },
  { id: 3, title: 'Chapter 3', subtitle: 'Reading in the Wild' },
  { id: 4, title: 'Chapter 4', subtitle: 'Writing Shavian' },
  {
    id: 5,
    title: 'Chapter 5',
    subtitle: 'Fluency & Beyond',
    comingSoon: true,
    blurb: 'Speed, longer stories, accents, and free writing — putting it all together.',
  },
];

function shuffle<T>(items: T[]): T[] {
  if (items.length < 2) return [...items];
  // Fisher-Yates, re-rolled until the order actually changes, so tiles and
  // options never render in their authored order (where the answer, always
  // listed first, could just be tapped straight through). Capped so a set of
  // otherwise-identical items can't loop forever.
  let result = [...items];
  for (let attempt = 0; attempt < 20; attempt++) {
    result = [...items];
    for (let i = result.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [result[i], result[j]] = [result[j], result[i]];
    }
    if (result.some((value, i) => value !== items[i])) break;
  }
  return result;
}

export function shuffleExerciseOptions(exercise: Exercise): Exercise {
  if (exercise.type === 'choice') {
    return { ...exercise, options: shuffle(exercise.options) };
  }
  if (exercise.type === 'listen') {
    // Dictation has nothing to shuffle — the keyboard is the exercise.
    return exercise.options ? { ...exercise, options: shuffle(exercise.options) } : exercise;
  }
  if (exercise.type === 'sort') {
    // `answer` runs parallel to `items`, so they have to move together or the
    // shuffle would silently reassign every word to the wrong bucket.
    const order = shuffle(exercise.items.map((_, i) => i));
    return {
      ...exercise,
      items: order.map((i) => exercise.items[i]),
      answer: order.map((i) => exercise.answer[i]),
    };
  }
  if (exercise.type === 'build' || exercise.type === 'arrange') {
    return { ...exercise, tiles: shuffle(exercise.tiles) };
  }
  if (
    exercise.type === 'complete' ||
    exercise.type === 'fill' ||
    exercise.type === 'cloze'
  ) {
    return { ...exercise, bank: shuffle(exercise.bank) };
  }
  if (exercise.type === 'match') {
    // Shuffle each column independently so pairs never line up row-to-row.
    return {
      ...exercise,
      leftOrder: shuffle(exercise.leftOrder),
      rightOrder: shuffle(exercise.rightOrder),
    };
  }
  return exercise;
}

export async function getLessonExercises(id: number): Promise<Exercise[]> {
  const lesson = await loadLesson(id);
  if (!lesson) return [];
  return lesson.exercises.map((exercise) => shuffleExerciseOptions({ ...exercise }));
}

/**
 * Warm a lesson's chunk without using it. The dashboard calls this for the
 * lesson its Continue card would open, so the common path stays instant.
 */
export function prefetchLesson(id: number): void {
  void loaders[id]?.();
}

export type { Exercise, LessonMeta, LessonFile } from './types';
